#define MOTOR_MIN_PWM -120  // 6v aprox with 12v input
#define MOTOR_MAX_PWM 120

// DISTANCE AND SPEED RULES TO AVOID A COLISION
#define STOP_DISTANCE_FRONT 60
#define STOP_DISTANCE_SIDES 30
#define WARNING_DISTANCE_FRONT 80
#define WARNING_DISTANCE_SIDES 50

#define DEBUG 0

#define LOG_DATA 0